spring:
  cloud:
    stream:
      bindings:
        bindingKafka-in-0:
          destination: batch-in-topic
          group: batch-in
          consumer:
            batch-mode: true

        targetBindingKafka-out-0:
          destination: batch-out-topic
  kafka:
    producer:
      acks: all
    consumer:
      auto-offset-reset: earliest
